[[telnet]]
arch = "aarch64"
git-tree-sha1 = "0fad1d98dd7edbbe68bf1cb5b65be25d28eb6160"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "77bcf7f08816b683f85956e652569623993b13632dce23abe1c18df978882f92"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.aarch64-linux-gnu.tar.gz"
[[telnet]]
arch = "aarch64"
git-tree-sha1 = "388725faf7d3870e39cd44df5a47820c16c5a4e9"
libc = "musl"
os = "linux"

    [[telnet.download]]
    sha256 = "312e28c7960ff98f81f5b67ee9decd59bf29e9bcd4c32533c8619b274445e379"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.aarch64-linux-musl.tar.gz"
[[telnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b35a146ffd1f797dcb18d68ef67fcc44cfe2aeb5"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "b2213aef860bfe869fedbb2dce960f7991bec20b7897eb85ff23b43f171389e3"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.armv6l-linux-gnueabihf.tar.gz"
[[telnet]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc18a35d2b829ddeaf71b3889364fa8d009f904c"
libc = "musl"
os = "linux"

    [[telnet.download]]
    sha256 = "b016e88773f96858c207283fdde1399d4692d85e6946fec35855c5c39881d4f7"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.armv6l-linux-musleabihf.tar.gz"
[[telnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da43544b4163774bdef7f0b07660db7ec960e01d"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "f35a1c1c630c4c88292ef8379f876cb9779ae5e6cdade7840c1cca666d0ff9b2"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.armv7l-linux-gnueabihf.tar.gz"
[[telnet]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "309f3d7f7d41c671c9c06c6cbce2f06d16ece360"
libc = "musl"
os = "linux"

    [[telnet.download]]
    sha256 = "ada8a8ad2f53679ff57b81d4c6e9e6616dc310afa1b68252c73682b291a68642"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.armv7l-linux-musleabihf.tar.gz"
[[telnet]]
arch = "i686"
git-tree-sha1 = "22e70524b02535f2fad4b7924227a8cd0f2cdd72"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "9d9e05a892da3c9ff150631bcaf755a86612c5b374e2756de797e1306d917bbc"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.i686-linux-gnu.tar.gz"
[[telnet]]
arch = "i686"
git-tree-sha1 = "84efa738ac1164ccee4b9e69e01d99b4ab109905"
libc = "musl"
os = "linux"

    [[telnet.download]]
    sha256 = "6bcd42559202a29f754c28f91550690d8fe0fd9c289aca12e3cbfcc222f207c8"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.i686-linux-musl.tar.gz"
[[telnet]]
arch = "powerpc64le"
git-tree-sha1 = "d81b64edaa5e406251948ef825a9c1150569b126"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "b8ac727a68ed19274767f7ec430a890fba1ef5d7a5d50f791151e5c1b62d0d39"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.powerpc64le-linux-gnu.tar.gz"
[[telnet]]
arch = "riscv64"
git-tree-sha1 = "4e40109c2b5f0c91e797442aeb6e6df9c1a56c08"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "f1b05d013f08532fd8d713b42670f7b051896e110ab9a29917afdfea5ca2d2e0"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.riscv64-linux-gnu.tar.gz"
[[telnet]]
arch = "x86_64"
git-tree-sha1 = "3d58d87a06832d7cf0c28b45c3164ef0776ff132"
libc = "glibc"
os = "linux"

    [[telnet.download]]
    sha256 = "d68c97c68d6ebd48e073167a0e983e9b8c2afaf70cc397bda10ddfcb5ed599ec"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.x86_64-linux-gnu.tar.gz"
[[telnet]]
arch = "x86_64"
git-tree-sha1 = "9923199c8c68da7a325204438a3d6a734a5778e2"
libc = "musl"
os = "linux"

    [[telnet.download]]
    sha256 = "3143269965c906fea43c7c8cf126b7f16a37c135cdd8546564455b55bbd435ec"
    url = "https://github.com/JuliaBinaryWrappers/telnet_jll.jl/releases/download/telnet-v2.6.0+0/telnet.v2.6.0.x86_64-linux-musl.tar.gz"
